version: '3'

services:
  server:
    command: ['npm', 'start']
    image: 'node:8.2'
    volumes:
      - './:/usr/src/app'
    working_dir: '/usr/src/app'
    ports: 
      - '3000:3000'
    environment:
      APP_PORT: '3000'
    depends_on: 
      - 'mongo'
      - 'redis'
  mongo:
    image: 'mongo:3.0'
    ports:
      - '27017'
  redis:
    image: 'redis:3.2'
    ports: 
      - '6379'

